name: A workflow for my My Demo Website 
on:
  workflow_dispatch:

jobs: 
 build-job: 
  name: Hello world action 
  runs-on: ubuntu-latest 
  steps: 
  - uses: actions/checkout@v1 
    name: Check out code 
  - name: Echo Hello World
    run: echo Hello World
  - name: Index.html Content
    run: |
         echo "This is line 1"
         echo "This is line 2"
         cat Index.html
         cat courses.html
